apiVersion: v1
kind: Service
metadata:
  name: web-app-service
  labels:
    app: web-app
spec:
  selector:
    app: web-app
  ports:
   - name: http
     port: 80
     targetPort: 80
  type: LoadBalancer

##########

apiVersion: v1
kind: ConfigMap
metadata:
  name: web-app-config
data:
  index.html: |
            <!doctype html>
            <html lang="en">
            <head>
            <meta charset="utf-8">
            <title>Web Application</title>
            </head>
            <body>
            <h1 style="text-align: center">Hello from Azure Kubernetes Service!</h1>
            </body>
            </html>

##########

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deployment
  labels:
    app: web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      volumes:
         - name: web-content
           configMap:
             name: web-app-config
      containers:
      - name: web-app-container
        image: nginx:stable
        volumeMounts:
        - name: web-content
          mountPath: /usr/share/nginx/html
        ports:
        - name: http
          containerPort: 80